# Content

###
# @name get
GET localhost:8081/content/5
Content-Type: application/json

#{
#  "id": 1,
#  "title": "UPDATE заголовок контента",
#  "body": "Текст контента, который возможно надо поменять)",
#  "status": "WAITING",
#  "published": false,
#  "_links": {
#    "self": {
#      "href": "http://localhost:8080/content/1"
#    },
#    "approve": {
#      "href": "http://localhost:8080/content/approve/1"
#    },
#    "update": {
#      "href": "http://localhost:8080/content/update/1"
#    },
#    "delete": {
#      "href": "http://localhost:8080/content/delete/1"
#    }
#  }
#}

###
# @name post
POST localhost:8081/content
Content-Type: application/json

{
  "title": "Заголовок заголовка ",
  "body": "Текст, спорт возможно надо поменять. Текст, который возможно надо поменять",
  "userId": "1"
}

###
# @name published
PATCH localhost:8081/content/published/1

###
# @name approve
PATCH localhost:8081/content/approve/4

###
# @name New Request
DELETE localhost:8081/content/delete/1

###
# @name update
PATCH localhost:8081/content/update/1
Content-Type: application/json

{
  "id": 2,
  "title": "UPDATE заголовок контента",
  "body": "Текст контента, который возможно надо поменять)Текст контента, который возможно надо поменять)Текст контента, который возможно надо поменять)Текст контента, который ",
  "status": "REJECTED",
  "published": false
}

###
# @name New Request
GET localhost:8081/


###
# @name user post
POST localhost:8081/user
Content-Type: application/json

{
  "username": "username123",
  "email": "email",
  "role": 0
}

###
# @name user get
GET localhost:8081/responses/2

###
# @name user get
GET localhost:8081/user